---
- name: "Disable ge-0/0/3 on R1 Device" 
  hosts: r1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: "Configure op script"
      juniper_junos_config:
        config_mode: "private"
        load: "set"
        lines:
          - "set interfaces ge-0/0/3 disable"   
      register: response
    - name: "Print the config changes"
      debug:
        var: response.diff_lines

- name: R1 interface and route status
  hosts: r1
  connection: local
  gather_facts: false

  tasks:

    - name: Running checks on r1
      junos_command:
        commands:
          - show route protocol static
          - show int ge-0/0/3 |match Down
        display: text
      register: output

    - debug: var=output.stdout_lines       
      
