---
- name: Load and commit configuration data on a device running Junos OS
  hosts: r1-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r1_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r2-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r2_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r3-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r3_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r4-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r4_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r5-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r5_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r6-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r6_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r7-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r7_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
- name: Load and commit configuration data on a device running Junos OS
  hosts: r8-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        format: "text"
        load: "set"
        src: "tasks/r8_tasks.cfg"
        comment: "Configuring op script with Ansible"
        ignore_warning: true
      register: response
    - name: Print the response
      debug:
        var: response
